/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Encounter;
import model.Person;
import model.SystemAdmin;
import model.VitalSigns;

/**
 *
 * @author manavhirey
 */
public class EncounterHistory extends javax.swing.JPanel {
    /**
     * Creates new form EncounterHistory
     */
    private Person loggedPerson;
    public EncounterHistory(Person loggedInPerson) {
        initComponents();
        this.loggedPerson = loggedInPerson;
        if(loggedPerson.getRole() == Person.UserRole.PATIENT){
            bodyTempTxt.setEditable(false);
            bpTxt.setEditable(false);
            pulseTxt.setEditable(false);
            diagTxt.setEditable(false);
            noteTxt.setEditable(false);
            deleteBtn.setEnabled(false);
            updateBtn.setEnabled(false);
        }else if(loggedPerson.getRole() != Person.UserRole.SYS_ADMIN){
            deleteBtn.setEnabled(false);
        }
        populateTable();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        encounterTbl = new javax.swing.JTable();
        loginLabel = new javax.swing.JLabel();
        loginLabel1 = new javax.swing.JLabel();
        loginLabel2 = new javax.swing.JLabel();
        loginLabel3 = new javax.swing.JLabel();
        loginLabel4 = new javax.swing.JLabel();
        loginLabel5 = new javax.swing.JLabel();
        bpTxt = new javax.swing.JTextField();
        bodyTempTxt = new javax.swing.JTextField();
        pulseTxt = new javax.swing.JTextField();
        noteTxt = new javax.swing.JTextField();
        diagTxt = new javax.swing.JTextField();
        viewBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        patientSearch = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(44, 51, 51));

        encounterTbl.setBackground(new java.awt.Color(44, 51, 51));
        encounterTbl.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        encounterTbl.setForeground(new java.awt.Color(231, 246, 242));
        encounterTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Appointment ID", "Date", "Time", "Doctor", "Hospital"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        encounterTbl.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(encounterTbl);

        loginLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(231, 246, 242));
        loginLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        loginLabel.setText("Pulse:");

        loginLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        loginLabel1.setForeground(new java.awt.Color(165, 201, 202));
        loginLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        loginLabel1.setText("Encounter History");

        loginLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        loginLabel2.setForeground(new java.awt.Color(231, 246, 242));
        loginLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        loginLabel2.setText("Body Temperature:");

        loginLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        loginLabel3.setForeground(new java.awt.Color(231, 246, 242));
        loginLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        loginLabel3.setText("Blood pressure:");

        loginLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        loginLabel4.setForeground(new java.awt.Color(231, 246, 242));
        loginLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        loginLabel4.setText("Diagnosis:");

        loginLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        loginLabel5.setForeground(new java.awt.Color(231, 246, 242));
        loginLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        loginLabel5.setText("Note:");

        bpTxt.setBackground(new java.awt.Color(231, 246, 242));
        bpTxt.setForeground(new java.awt.Color(57, 91, 100));

        bodyTempTxt.setBackground(new java.awt.Color(231, 246, 242));
        bodyTempTxt.setForeground(new java.awt.Color(57, 91, 100));

        pulseTxt.setBackground(new java.awt.Color(231, 246, 242));
        pulseTxt.setForeground(new java.awt.Color(57, 91, 100));

        noteTxt.setBackground(new java.awt.Color(231, 246, 242));
        noteTxt.setForeground(new java.awt.Color(57, 91, 100));

        diagTxt.setBackground(new java.awt.Color(231, 246, 242));
        diagTxt.setForeground(new java.awt.Color(57, 91, 100));

        viewBtn.setBackground(new java.awt.Color(165, 201, 202));
        viewBtn.setForeground(new java.awt.Color(57, 91, 100));
        viewBtn.setText("View");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });

        updateBtn.setBackground(new java.awt.Color(165, 201, 202));
        updateBtn.setForeground(new java.awt.Color(57, 91, 100));
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(165, 201, 202));
        deleteBtn.setForeground(new java.awt.Color(57, 91, 100));
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(231, 246, 242));
        jLabel1.setText("Search Patient:");

        patientSearch.setBackground(new java.awt.Color(231, 246, 242));
        patientSearch.setForeground(new java.awt.Color(57, 91, 100));

        searchBtn.setBackground(new java.awt.Color(165, 201, 202));
        searchBtn.setForeground(new java.awt.Color(57, 91, 100));
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(patientSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchBtn))
                    .addComponent(loginLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(loginLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(diagTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(loginLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(noteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(loginLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(loginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(loginLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(bpTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bodyTempTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pulseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(80, 80, 80))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(viewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 749, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(loginLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn)
                    .addComponent(jLabel1))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginLabel2)
                    .addComponent(bodyTempTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginLabel3)
                    .addComponent(bpTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginLabel)
                    .addComponent(pulseTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginLabel4)
                    .addComponent(diagTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginLabel5)
                    .addComponent(noteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(164, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        // TODO add your handling code here:
        int selected = encounterTbl.getSelectedRow();
        
        if (selected < 0){
            JOptionPane.showMessageDialog(this, "Please select a row to add VitalSigns.");
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) encounterTbl.getModel();
        Encounter selectedEnc = SystemAdmin.encHistRef.getPastList().get(selected);
        
        bodyTempTxt.setText(String.valueOf(selectedEnc.getVital().getTemp()));
        bpTxt.setText(String.valueOf(selectedEnc.getVital().getBp()));
        pulseTxt.setText(String.valueOf(selectedEnc.getVital().getPulse()));
        diagTxt.setText(String.valueOf(selectedEnc.getVital().getDiagnosis()));
        noteTxt.setText(String.valueOf(selectedEnc.getVital().getNote()));
        
        JOptionPane.showMessageDialog(this, "Encounter Fetched. Please Enter Vitals.");
    }//GEN-LAST:event_viewBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        int selected = encounterTbl.getSelectedRow();
        
        if (selected < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to update!");
            return;
        }
        
        double bodyTemp = Double.parseDouble(bodyTempTxt.getText());
        double name = Double.parseDouble(bpTxt.getText());
        double pulse = Double.parseDouble(pulseTxt.getText());
        String diag = diagTxt.getText();
        String note = noteTxt.getText();
        VitalSigns vitals = new VitalSigns(bodyTemp,name,pulse,diag,note);
        
        Encounter enc = SystemAdmin.encHistRef.getPastList().get(selected);
        
        enc.setVital(vitals);
        
        bodyTempTxt.setText("");
        bpTxt.setText("");
        pulseTxt.setText("");
        diagTxt.setText("");
        noteTxt.setText("");
        
        JOptionPane.showMessageDialog(this, "Patient VitalSigns Updated.");

    }//GEN-LAST:event_updateBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        if(patientSearch == null){
            JOptionPane.showMessageDialog(this, "Enter Keywords to search.");
        }else{
            String search = patientSearch.getText();
            populateBySearch(search);
        }
        
    }//GEN-LAST:event_searchBtnActionPerformed

    private void populateTable(){
         DefaultTableModel model = (DefaultTableModel) encounterTbl.getModel();
        model.setRowCount(0);
        
        for(Encounter enc: SystemAdmin.encHistRef.getPastList()){
            
            Object[] row = new Object[5];
            row[0] = enc.getAppointmentID();
            //row[0] = ne.getEmployeeId();
            row[1] = enc.getDate();
            row[2] = enc.getTime();
            row[3] = enc.getDoctorName().getName();
            row[4] = enc.getDoctorName().getNameHospital().getHospitalName();

            model.addRow(row);
        }
    }
    
    private void populateBySearch(String search){
        DefaultTableModel model = (DefaultTableModel) encounterTbl.getModel();
        model.setRowCount(0);
        
        for(Encounter enc: SystemAdmin.encHistRef.getPastList()){
            if(search.equals(enc.getPersonName().getName())){
                Object[] row = new Object[5];
                row[0] = enc.getAppointmentID();
                //row[0] = ne.getEmployeeId();
                row[1] = enc.getDate();
                row[2] = enc.getTime();
                row[3] = enc.getDoctorName().getName();
                row[4] = enc.getDoctorName().getNameHospital().getHospitalName();

            model.addRow(row);
            }
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bodyTempTxt;
    private javax.swing.JTextField bpTxt;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField diagTxt;
    private javax.swing.JTable encounterTbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JLabel loginLabel1;
    private javax.swing.JLabel loginLabel2;
    private javax.swing.JLabel loginLabel3;
    private javax.swing.JLabel loginLabel4;
    private javax.swing.JLabel loginLabel5;
    private javax.swing.JTextField noteTxt;
    private javax.swing.JTextField patientSearch;
    private javax.swing.JTextField pulseTxt;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton updateBtn;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables
}
