/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.City;
import model.Person;
import model.SystemAdmin;

/**
 *
 * @author manavhirey
 */
public class ManageCity extends javax.swing.JPanel {

    /**
     * Creates new form ManageCity
     */
    public static Person loggedPerson;
    private static ManageCity manageCity;
            
    public ManageCity(Person loggedInPerson) {
        initComponents();
        this.loggedPerson = loggedInPerson;
        deleteBtn.setVisible(false);
        this.loggedPerson = loggedInPerson;
        if(loggedInPerson.getRole().equals(SystemAdmin.UserRole.SYS_ADMIN)){
            deleteBtn.setVisible(true);
        }
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        cityIdTxt = new javax.swing.JTextField();
        cityTxt = new javax.swing.JTextField();
        comTxt = new javax.swing.JTextField();
        deleteBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        viewBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        createBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        cityTbl = new javax.swing.JTable();
        loginLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(44, 51, 51));

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(231, 246, 242));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Community:");

        cityIdTxt.setBackground(new java.awt.Color(231, 246, 242));
        cityIdTxt.setForeground(new java.awt.Color(57, 91, 100));
        cityIdTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cityIdTxtFocusLost(evt);
            }
        });

        cityTxt.setBackground(new java.awt.Color(231, 246, 242));
        cityTxt.setForeground(new java.awt.Color(57, 91, 100));

        comTxt.setBackground(new java.awt.Color(231, 246, 242));
        comTxt.setForeground(new java.awt.Color(57, 91, 100));

        deleteBtn.setBackground(new java.awt.Color(165, 201, 202));
        deleteBtn.setForeground(new java.awt.Color(57, 91, 100));
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        updateBtn.setBackground(new java.awt.Color(165, 201, 202));
        updateBtn.setForeground(new java.awt.Color(57, 91, 100));
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        viewBtn.setBackground(new java.awt.Color(165, 201, 202));
        viewBtn.setForeground(new java.awt.Color(57, 91, 100));
        viewBtn.setText("View");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(231, 246, 242));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("City ID:");

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(231, 246, 242));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("City:");

        createBtn.setBackground(new java.awt.Color(165, 201, 202));
        createBtn.setForeground(new java.awt.Color(57, 91, 100));
        createBtn.setText("Create");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });

        cityTbl.setBackground(new java.awt.Color(44, 51, 51));
        cityTbl.setForeground(new java.awt.Color(231, 246, 242));
        cityTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "City ID", "City Name", "Community"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cityTbl.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(cityTbl);

        loginLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        loginLabel1.setForeground(new java.awt.Color(165, 201, 202));
        loginLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        loginLabel1.setText("City Manager");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 942, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cityIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(29, 29, 29)
                                .addComponent(comTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(267, 267, 267))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(createBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(viewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(loginLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cityIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(comTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        int selected = cityTbl.getSelectedRow();

        if (selected < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to delete.");
            return;
        }

        City city = SystemAdmin.cityDir.getCityDir().get(selected);

        SystemAdmin.cityDir.getCityDir().remove(city);

        populateTable();

        cityIdTxt.setText("");
        cityTxt.setText("");
        comTxt.setText("");
        createBtn.setEnabled(true);
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        int selected = cityTbl.getSelectedRow();

        if (selected < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to update!");
            return;
        }

        long cityID = Long.parseLong(cityIdTxt.getText());
        String cityName = cityTxt.getText();

        //      City city = new City(cityName, cityID, communityNames);
        City city = SystemAdmin.cityDir.getCityDir().get(selected);

        city.setCityID(cityID);
        city.setName(cityName);

        ArrayList<String> communityNames = city.getCity();
        communityNames.clear();

        String [] cNames = comTxt.getText().split(",");

        for(int i=0; i<cNames.length; i++)
        communityNames.add(cNames[i]);

        populateTable();

        cityIdTxt.setText("");
        cityTxt.setText("");
        comTxt.setText("");
        createBtn.setEnabled(true);
    }//GEN-LAST:event_updateBtnActionPerformed

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        // TODO add your handling code here:
        int selected = cityTbl.getSelectedRow();

        if (selected < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to view.");
            return;
        }

        City city = SystemAdmin.cityDir.getCityDir().get(selected);

        cityIdTxt.setText(String.valueOf(city.getCityID()));
        cityTxt.setText(String.valueOf(city.getName()));

        String names = "";
        for(String c : city.getCity())
        names += c+",";
        names = names.substring(0, names.length()-1);
        comTxt.setText(names);
        createBtn.setEnabled(false);
    }//GEN-LAST:event_viewBtnActionPerformed

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
        long cityID = Long.parseLong(cityIdTxt.getText());
        String cityName = cityTxt.getText();
        String [] cNames = comTxt.getText().split(",");
        ArrayList<String> communityNames = new ArrayList<String>();
        for(int i=0; i<cNames.length; i++)
        communityNames.add(cNames[i]);
        City city = new City(cityName, cityID, communityNames);
        SystemAdmin.cityDir.getCityDir().add(city);

        JOptionPane.showMessageDialog(this, "New City Details Added Successfully!");

        cityIdTxt.setText("");
        cityTxt.setText("");
        comTxt.setText("");
        populateTable();
    }//GEN-LAST:event_createBtnActionPerformed

    private void cityIdTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cityIdTxtFocusLost
        // TODO add your handling code here:
        if(!cityIdTxt.getText().equals("")){
            List<Long> cityList = SystemAdmin.cityDir.getCityDir().stream().map(x -> x.getCityID()).toList();
            if(cityList.contains(Long.parseLong(cityIdTxt.getText()))){
                JOptionPane.showMessageDialog(this, "CityID already in use.");
            }
        }
    }//GEN-LAST:event_cityIdTxtFocusLost

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) cityTbl.getModel();
        model.setRowCount(0);
                for (City city : SystemAdmin.cityDir.getCityDir()) {

            Object[] rowData = new Object[3];
            rowData[0] = city.getCityID();
            rowData[1] = city.getName();
            String names = "";
            for(String c : city.getCity())
                names += c+",";
            names = names.substring(0, names.length()-1);
            rowData[2] = names;
            model.addRow(rowData);

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cityIdTxt;
    private javax.swing.JTable cityTbl;
    private javax.swing.JTextField cityTxt;
    private javax.swing.JTextField comTxt;
    private javax.swing.JButton createBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel loginLabel1;
    private javax.swing.JButton updateBtn;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables
}
